# Generated by Django 5.1.2 on 2024-10-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluegreen', '0002_greenshuttlestopindex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueshuttle',
            name='number_of_passangers_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blueshuttle',
            name='number_of_passangers_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='greenshuttle',
            name='number_of_passangers_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='greenshuttle',
            name='number_of_passangers_out',
            field=models.IntegerField(default=0),
        ),
    ]
