# Generated by Django 5.1.2 on 2024-10-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluegreen', '0003_alter_blueshuttle_number_of_passangers_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueshuttle',
            name='number_of_passangers_in',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blueshuttle',
            name='number_of_passangers_out',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='greenshuttle',
            name='number_of_passangers_in',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='greenshuttle',
            name='number_of_passangers_out',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
