# Generated by Django 5.1.2 on 2024-10-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluegreen', '0005_laststopblueoccupancy_laststopgreenoccupancy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationAdder',
        ),
        migrations.AlterModelOptions(
            name='blueshuttle',
            options={'verbose_name': 'Blue Shuttle Entry', 'verbose_name_plural': 'Blue Shuttle Entries'},
        ),
        migrations.AlterModelOptions(
            name='greenshuttle',
            options={'verbose_name': 'Green Shuttle Entry', 'verbose_name_plural': 'Green Shuttle Entries'},
        ),
        migrations.AlterModelOptions(
            name='greenshuttlestopindex',
            options={'verbose_name': 'Green Shuttle Stop Index', 'verbose_name_plural': 'Green Shuttle Stop Index '},
        ),
        migrations.AlterModelOptions(
            name='laststopblueoccupancy',
            options={'verbose_name': 'Blue Last Stop Occupancy', 'verbose_name_plural': 'Blue Last Stop Occupancy'},
        ),
        migrations.AlterModelOptions(
            name='laststopgreenoccupancy',
            options={'verbose_name': 'Green Last Stop Occupancy', 'verbose_name_plural': 'Green Last Stop Occupancy'},
        ),
        migrations.AlterModelOptions(
            name='shuttle',
            options={'verbose_name': 'Shuttle Detail', 'verbose_name_plural': 'Shuttle Details'},
        ),
        migrations.AlterModelOptions(
            name='shuttlestopindex',
            options={'verbose_name': 'Blue Shuttle Stop Index', 'verbose_name_plural': 'Blue Shuttle Stop Index'},
        ),
        migrations.AlterField(
            model_name='blueshuttle',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
