# Generated by Django 5.1.2 on 2024-10-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluegreen', '0006_delete_locationadder_alter_blueshuttle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueshuttle',
            name='occupancy_detail',
            field=models.IntegerField(default=0),
        ),
    ]
